server:
  # O Railway define a porta automaticamente na vari√°vel $PORT
  port: ${PORT:8080}

spring:
  application:
    name: saas-fitness-b2b

  datasource:
    # Na nuvem, o Railway vai injetar essas vari√°veis automaticamente
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # üåü A M√ÅGICA DO E-MAIL FICA AQUI (O JavaMailSender precisa disto para existir)
  mail:
    host: smtp.gmail.com
    port: 587
    username: panuccidev@gmail.com
    password: treinodexbackend
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true

api:
  security:
    token:
      secret: ${JWT_SECRET:MinhaSenhaSuperSecretaDeDesenvolvimento123456789012}

app:
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}